---
sudo: false

language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
#  - npm run test
  - npm run doc

deploy:
  - provider: script
    skip_cleanup: true
    script: node_modules/@geoblocks/base/scripts/publish-npm --force
    on:
      tags: true
