---
sudo: false

language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

script:
  - npm run test
  # Test minimal versions
  - sed --in-place 's/>=//g' package.json
  - sed --in-place 's/\^//g' package.json
  - sed --in-place 's/~//g' package.json
  - npm install
  - npm run test
